[tool.poetry]
name = "ibenthos-pt-ifdo-gui"
version = "0.1.0"
description = ""
authors = ["Brendan Do <brendan.do@csiro.au>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyqt6 = "^6.8.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
